version: '3'
services:
  betaum:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: servidor-dhcp
    network_mode: host
    cap_add: 
      - NET_ADMIN
    ports:
      - "67:67/udp"
    restart: always